enum ConfigKey {
  NAME = 'NAME',
  PORT = 'PORT',
  VERSION = 'VERSION',
  BASE_PATH = 'BASE_PATH',
  JWT_SECRET_ACCESS_TOKEN_KEY = 'JWT_SECRET_ACCESS_TOKEN_KEY',
  JWT_SECRET_REFRESH_TOKEN_KEY = 'JWT_SECRET_REFRESH_TOKEN_KEY',
  TOKEN_EXPIRED_IN = 'TOKEN_EXPIRED_IN',
  REFRESH_TOKEN_EXPIRED_IN = 'REFRESH_TOKEN_EXPIRED_IN',
  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',
  LOG_LEVEL = 'LOG_LEVEL',
  LOG_ROOT_FOLDER = 'LOG_ROOT_FOLDER',
  CORS_WHITELIST = 'CORS_WHITELIST',
  WEB_APP_BASE_URL = 'WEB_APP_BASE_URL',
  AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY',
  AWS_REGION = 'AWS_REGION',
  AWS_S3_BUCKET = 'AWS_S3_BUCKET',
  AWS_S3_DOMAIN = 'AWS_S3_DOMAIN',
}

export default ConfigKey;
