version: '3.8'
services:
    api_gateway:
        build: ./api-gateway
        networks:
            - mysql
        ports:
            - 3000:3000

        env_file:
          - ./api-gateway/.env

    auth_service:
        build: ./auth-service
        networks:
            - mysql
        ports:
            - 3001:3001
        env_file:
          - ./auth-service/.env

    user_service:
        build: ./user-service
        networks:
            - mysql
        ports:
            - 3002:3002
        depends_on:
            - mysql
        env_file:
          - ./user-service/.env

    post_service:
      build: ./post-service
      networks:
        - mysql
      ports:
        - 3003:3003
      depends_on:
        - mysql
      env_file:
        - ./post-service/.env
    # chat_service:
    #   build: ./chat-service
    #   networks:
    #     - mysql
    #   ports:
    #     - 3004:3004

    mysql:
        image: mysql:8.0.32
        environment:
            - MYSQL_ROOT_PASSWORD=123456
        ports:
            - 3308:3306
        networks:
            - mysql

        volumes:
            - proteam-value:/var/lib/mysql
volumes:
    proteam-value:

networks:
    mysql:
