enum ConfigKey {
  NAME = 'NAME',
  PORT = 'PORT',
  VERSION = 'VERSION',
  BASE_PATH = 'BASE_PATH',
  JWT_SECRET_ACCESS_TOKEN_KEY = 'JWT_SECRET_ACCESS_TOKEN_KEY',
  JWT_SECRET_REFRESH_TOKEN_KEY = 'JWT_SECRET_REFRESH_TOKEN_KEY',
}

export default ConfigKey;
